### ISSUE TITLE
stdin

### ISSUE THREAD

**Issue by konsumer** [konsumer/easywasi#1]
This should have a nice wrapper for `stdin` like I have for `stdout` and `stderr`. Essentially, on every read, it should call `stdin` which returns a `Uint8Array`, and have a default implementation that returns an empty `Uint8Array`. I should probly also make a couple examples, like "pipe a file into stdin".

**Comment by konsumer** [comment]
this should be implemented in [d244fe7](https://github.com/konsumer/easywasi/commit/d244fe7979412aaee163251e110590f4475a61aa)

**Comment by guest271314** [comment]
Doesn't read `stdin` when using `node`.

**Comment by konsumer** [comment]
There plenty of solutions for wasi for node that might work better for you. The focus of this project is the browser.

That said, you can implement stdin function to read `process.stdin` if you want that.

**Comment by guest271314** [comment]
I did. For Deno, Node.js, and Bun https://github.com/guest271314/deno-wasi. I was just checking out your gear see what you did. I have not dove in to the browser implementation part, yet. I'm sure it's doable.

**Comment by guest271314** [comment]
Pardon, this branch https://github.com/guest271314/deno-wasi/tree/runtime-agnostic-nodejs-api.

**Comment by guest271314** [comment]
ECMA-262 doesn't specify I/O for JavaScript. One option is to use `args` for input. For the browser implementation, the closest to `stdin` that I can think of is `import` or `import()`; or a URL with query string parameters; or Origin Private File System with `navigator.storage.getDirectory()` to read an write files; or use a resizable `ArrayBuffer` for writing to then resize to `0`.

**Comment by konsumer** [comment]
This is a closed issue, and not related to what you are talking about. This issue is about the [stdio callbacks](https://github.com/konsumer/easywasi/blob/main/docs/easywasi.js#L193-L207) before I implemented them. They are done now, and this issue is closed. If you already have your own WASI, I'm not sure why you are suggesting mine do anything different with stdio, but it works fine for my usecases, so I would need some good reasons to change it, and that discussion would be better suited to a new issue, anyway (because this one is resolved.)

Either way, automatically reading stdin or reading/writing a filesystem or anything like that is not part of what I am doing here, so I don't think it will work how you are imagining, for my library. Like the purpose of this lib is you BYO everything, and nothing is automatic (other than reasonable defaults that are easy to override for stdout/err, in all js environments) which makes it easier to work with (especially if you need to override how files or stdio works) and more secure, overall.

**Comment by guest271314** [comment]
I'm just checking out your gear. Good luck!

**Comment by konsumer** [comment]
you too!
